/**
 * Bundled demo dataset, generated from a real PSN export.
 * Used as a fallback so the dashboard renders without a live token.
 * Do not edit by hand — regenerate via scripts/gen-mock if the shape changes.
 */
import type { DashboardData } from "@/server/providers/account/snapshot";

export const demoDashboard: DashboardData = {
  profile: {
    onlineId: "Ernxst_",
    accountId: "demo",
    aboutMe: "Demo profile — your real data replaces this once you sign in.",
    isPlus: true,
    trophyLevel: 220,
    levelProgress: 70,
    earned: {
      platinum: 9,
      gold: 54,
      silver: 188,
      bronze: 887,
    },
    totalTrophies: 1138,
  },
  games: [
    {
      titleId: "DEMO-0",
      name: "Call of Duty®: Modern Warfare®",
      platform: "PS4",
      hours: 1253.62,
      playCount: 648,
      firstPlayed: "2020-03-18",
      lastPlayed: "2022-09-15",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 68,
        earned: { platinum: 0, gold: 3, silver: 9, bronze: 29 },
        total: 41,
        hasPlatinum: false,
        lastEarnedAt: "2022-09-15",
      },
    },
    {
      titleId: "DEMO-1",
      name: "FIFA 18",
      platform: "PS4",
      hours: 592.76,
      playCount: 482,
      firstPlayed: "2017-09-29",
      lastPlayed: "2018-09-06",
      category: "ps4_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 69,
        earned: { platinum: 0, gold: 3, silver: 9, bronze: 29 },
        total: 41,
        hasPlatinum: false,
        lastEarnedAt: "2018-09-06",
      },
    },
    {
      titleId: "DEMO-2",
      name: "Tom Clancy's The Division® 2",
      platform: "PS4",
      hours: 459.65,
      playCount: 440,
      firstPlayed: "2020-04-02",
      lastPlayed: "2026-06-24",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Tom Clancy",
      isApp: false,
      trophy: {
        progress: 70,
        earned: { platinum: 0, gold: 4, silver: 9, bronze: 29 },
        total: 42,
        hasPlatinum: false,
        lastEarnedAt: "2026-06-24",
      },
    },
    {
      titleId: "DEMO-3",
      name: "Call of Duty®: Black Ops 4",
      platform: "PS4",
      hours: 412.47,
      playCount: 326,
      firstPlayed: "2019-03-26",
      lastPlayed: "2020-05-11",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 71,
        earned: { platinum: 0, gold: 4, silver: 9, bronze: 30 },
        total: 43,
        hasPlatinum: false,
        lastEarnedAt: "2020-05-11",
      },
    },
    {
      titleId: "DEMO-4",
      name: "FIFA 22",
      platform: "PS4",
      hours: 380.79,
      playCount: 198,
      firstPlayed: "2021-10-10",
      lastPlayed: "2022-09-03",
      category: "ps4_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 72,
        earned: { platinum: 0, gold: 4, silver: 9, bronze: 30 },
        total: 43,
        hasPlatinum: false,
        lastEarnedAt: "2022-09-03",
      },
    },
    {
      titleId: "DEMO-5",
      name: "Grand Theft Auto V (PlayStation®5)",
      platform: "PS4",
      hours: 377.99,
      playCount: 262,
      firstPlayed: "2017-06-26",
      lastPlayed: "2025-05-22",
      category: "ps4_game",
      genre: "Open World",
      franchise: "Grand Theft Auto",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2025-05-22",
      },
    },
    {
      titleId: "DEMO-6",
      name: "Satisfactory",
      platform: "PS5",
      hours: 365.9,
      playCount: 167,
      firstPlayed: "2025-12-07",
      lastPlayed: "2026-06-25",
      category: "ps5_native_game",
      genre: "Survival/Craft",
      franchise: "Satisfactory",
      isApp: false,
      trophy: {
        progress: 74,
        earned: { platinum: 0, gold: 4, silver: 10, bronze: 31 },
        total: 45,
        hasPlatinum: false,
        lastEarnedAt: "2026-06-25",
      },
    },
    {
      titleId: "DEMO-7",
      name: "Minecraft",
      platform: "PS5",
      hours: 315.06,
      playCount: 118,
      firstPlayed: "2025-03-30",
      lastPlayed: "2026-02-25",
      category: "ps5_native_game",
      genre: "Survival/Craft",
      franchise: "Minecraft",
      isApp: false,
      trophy: {
        progress: 75,
        earned: { platinum: 0, gold: 4, silver: 10, bronze: 32 },
        total: 46,
        hasPlatinum: false,
        lastEarnedAt: "2026-02-25",
      },
    },
    {
      titleId: "DEMO-8",
      name: "Cyberpunk 2077",
      platform: "PS5",
      hours: 255.74,
      playCount: 213,
      firstPlayed: "2023-06-17",
      lastPlayed: "2025-01-26",
      category: "ps5_native_game",
      genre: "RPG",
      franchise: "Cyberpunk",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2025-01-26",
      },
    },
    {
      titleId: "DEMO-9",
      name: "NBA 2K19",
      platform: "PS4",
      hours: 237.88,
      playCount: 246,
      firstPlayed: "2018-09-15",
      lastPlayed: "2019-08-20",
      category: "ps4_game",
      genre: "Sports",
      franchise: "NBA 2K",
      isApp: false,
      trophy: {
        progress: 76,
        earned: { platinum: 0, gold: 4, silver: 10, bronze: 32 },
        total: 46,
        hasPlatinum: false,
        lastEarnedAt: "2019-08-20",
      },
    },
    {
      titleId: "DEMO-10",
      name: "Horizon Forbidden West",
      platform: "PS5",
      hours: 230.92,
      playCount: 163,
      firstPlayed: "2022-05-22",
      lastPlayed: "2025-06-19",
      category: "ps5_native_game",
      genre: "Open World",
      franchise: "Horizon",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2025-06-19",
      },
    },
    {
      titleId: "DEMO-11",
      name: "No Man's Sky",
      platform: "PS5",
      hours: 222.06,
      playCount: 266,
      firstPlayed: "2025-08-29",
      lastPlayed: "2025-12-09",
      category: "ps5_native_game",
      genre: "Survival/Craft",
      franchise: "No Man's Sky",
      isApp: false,
      trophy: {
        progress: 87,
        earned: { platinum: 0, gold: 4, silver: 11, bronze: 37 },
        total: 52,
        hasPlatinum: false,
        lastEarnedAt: "2025-12-09",
      },
    },
    {
      titleId: "DEMO-12",
      name: "FIFA 20",
      platform: "PS4",
      hours: 205.52,
      playCount: 178,
      firstPlayed: "2019-09-27",
      lastPlayed: "2020-09-22",
      category: "ps4_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 88,
        earned: { platinum: 0, gold: 4, silver: 11, bronze: 37 },
        total: 52,
        hasPlatinum: false,
        lastEarnedAt: "2020-09-22",
      },
    },
    {
      titleId: "DEMO-13",
      name: "Call of Duty®",
      platform: "PS5",
      hours: 197.83,
      playCount: 165,
      firstPlayed: "2022-11-16",
      lastPlayed: "2026-03-14",
      category: "ps5_native_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 89,
        earned: { platinum: 0, gold: 4, silver: 12, bronze: 37 },
        total: 53,
        hasPlatinum: false,
        lastEarnedAt: "2026-03-14",
      },
    },
    {
      titleId: "DEMO-14",
      name: "EA SPORTS FC™ 24",
      platform: "PS5",
      hours: 192.74,
      playCount: 139,
      firstPlayed: "2023-09-29",
      lastPlayed: "2024-09-07",
      category: "ps5_native_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 90,
        earned: { platinum: 0, gold: 5, silver: 12, bronze: 38 },
        total: 55,
        hasPlatinum: false,
        lastEarnedAt: "2024-09-07",
      },
    },
    {
      titleId: "DEMO-15",
      name: "NBA 2K21",
      platform: "PS4",
      hours: 163.36,
      playCount: 104,
      firstPlayed: "2021-06-02",
      lastPlayed: "2021-08-08",
      category: "unknown",
      genre: "Sports",
      franchise: "NBA 2K",
      isApp: false,
      trophy: {
        progress: 45,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 19 },
        total: 27,
        hasPlatinum: false,
        lastEarnedAt: "2021-08-08",
      },
    },
    {
      titleId: "DEMO-16",
      name: "Mass Effect™: Andromeda",
      platform: "PS4",
      hours: 153.01,
      playCount: 143,
      firstPlayed: "2026-04-22",
      lastPlayed: "2026-06-24",
      category: "ps4_game",
      genre: "RPG",
      franchise: "Mass Effect",
      isApp: false,
      trophy: {
        progress: 46,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 19 },
        total: 27,
        hasPlatinum: false,
        lastEarnedAt: "2026-06-24",
      },
    },
    {
      titleId: "DEMO-17",
      name: "Fortnite",
      platform: "PS4",
      hours: 149.62,
      playCount: 156,
      firstPlayed: "2017-10-20",
      lastPlayed: "2020-02-28",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Fortnite",
      isApp: false,
      trophy: {
        progress: 47,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 20 },
        total: 28,
        hasPlatinum: false,
        lastEarnedAt: "2020-02-28",
      },
    },
    {
      titleId: "DEMO-18",
      name: "Minecraft",
      platform: "PS4",
      hours: 131.83,
      playCount: 83,
      firstPlayed: "2019-01-12",
      lastPlayed: "2025-03-25",
      category: "ps4_game",
      genre: "Survival/Craft",
      franchise: "Minecraft",
      isApp: false,
      trophy: {
        progress: 48,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 20 },
        total: 28,
        hasPlatinum: false,
        lastEarnedAt: "2025-03-25",
      },
    },
    {
      titleId: "DEMO-19",
      name: "NBA 2K23",
      platform: "PS5",
      hours: 125.33,
      playCount: 162,
      firstPlayed: "2022-11-02",
      lastPlayed: "2023-08-22",
      category: "ps5_native_game",
      genre: "Sports",
      franchise: "NBA 2K",
      isApp: false,
      trophy: {
        progress: 49,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 21 },
        total: 29,
        hasPlatinum: false,
        lastEarnedAt: "2023-08-22",
      },
    },
    {
      titleId: "DEMO-20",
      name: "Shadow of the Tomb Raider",
      platform: "PS4",
      hours: 121.43,
      playCount: 97,
      firstPlayed: "2020-04-10",
      lastPlayed: "2024-09-20",
      category: "ps4_game",
      genre: "Action-Adventure",
      franchise: "Tomb Raider",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2024-09-20",
      },
    },
    {
      titleId: "DEMO-21",
      name: "EA SPORTS FC™ 26",
      platform: "PS5",
      hours: 90.98,
      playCount: 62,
      firstPlayed: "2025-09-20",
      lastPlayed: "2026-01-20",
      category: "ps5_native_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 34,
        earned: { platinum: 0, gold: 2, silver: 4, bronze: 14 },
        total: 20,
        hasPlatinum: false,
        lastEarnedAt: "2026-01-20",
      },
    },
    {
      titleId: "DEMO-22",
      name: "Rise of the Tomb Raider",
      platform: "PS4",
      hours: 76.9,
      playCount: 72,
      firstPlayed: "2021-04-17",
      lastPlayed: "2024-08-05",
      category: "ps4_game",
      genre: "Action-Adventure",
      franchise: "Tomb Raider",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2024-08-05",
      },
    },
    {
      titleId: "DEMO-23",
      name: "Forza Horizon 5",
      platform: "PS5",
      hours: 76.13,
      playCount: 132,
      firstPlayed: "2025-04-26",
      lastPlayed: "2026-02-25",
      category: "ps5_native_game",
      genre: "Racing",
      franchise: "Forza",
      isApp: false,
      trophy: {
        progress: 36,
        earned: { platinum: 0, gold: 2, silver: 5, bronze: 15 },
        total: 22,
        hasPlatinum: false,
        lastEarnedAt: "2026-02-25",
      },
    },
    {
      titleId: "DEMO-24",
      name: "Subnautica",
      platform: "PS4",
      hours: 75.78,
      playCount: 84,
      firstPlayed: "2021-04-01",
      lastPlayed: "2023-01-10",
      category: "ps4_game",
      genre: "Survival/Craft",
      franchise: "Subnautica",
      isApp: false,
      trophy: {
        progress: 37,
        earned: { platinum: 0, gold: 2, silver: 5, bronze: 16 },
        total: 23,
        hasPlatinum: false,
        lastEarnedAt: "2023-01-10",
      },
    },
    {
      titleId: "DEMO-25",
      name: "STAR WARS Jedi: Survivor™",
      platform: "PS5",
      hours: 69.29,
      playCount: 48,
      firstPlayed: "2026-02-23",
      lastPlayed: "2026-06-17",
      category: "ps5_native_game",
      genre: "Action-Adventure",
      franchise: "Star Wars",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2026-06-17",
      },
    },
    {
      titleId: "DEMO-26",
      name: "F1® 2019",
      platform: "PS4",
      hours: 67,
      playCount: 69,
      firstPlayed: "2020-04-09",
      lastPlayed: "2020-07-05",
      category: "ps4_game",
      genre: "Racing",
      franchise: "F1",
      isApp: false,
      trophy: {
        progress: 39,
        earned: { platinum: 0, gold: 2, silver: 5, bronze: 16 },
        total: 23,
        hasPlatinum: false,
        lastEarnedAt: "2020-07-05",
      },
    },
    {
      titleId: "DEMO-27",
      name: "God of War Ragnarök",
      platform: "PS5",
      hours: 65.13,
      playCount: 64,
      firstPlayed: "2022-11-09",
      lastPlayed: "2023-08-13",
      category: "ps5_native_game",
      genre: "Action-Adventure",
      franchise: "God of War",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2023-08-13",
      },
    },
    {
      titleId: "DEMO-28",
      name: "Anthem™",
      platform: "PS4",
      hours: 54.68,
      playCount: 67,
      firstPlayed: "2020-10-03",
      lastPlayed: "2023-09-15",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 41,
        earned: { platinum: 0, gold: 2, silver: 5, bronze: 17 },
        total: 24,
        hasPlatinum: false,
        lastEarnedAt: "2023-09-15",
      },
    },
    {
      titleId: "DEMO-29",
      name: "MONOPOLY PLUS",
      platform: "PS4",
      hours: 49.02,
      playCount: 48,
      firstPlayed: "2019-09-02",
      lastPlayed: "2026-05-08",
      category: "ps4_game",
      genre: "Indie/Casual",
      isApp: false,
      trophy: {
        progress: 42,
        earned: { platinum: 0, gold: 2, silver: 5, bronze: 18 },
        total: 25,
        hasPlatinum: false,
        lastEarnedAt: "2026-05-08",
      },
    },
    {
      titleId: "DEMO-30",
      name: "Subnautica: Below Zero",
      platform: "PS5",
      hours: 39.21,
      playCount: 46,
      firstPlayed: "2023-01-26",
      lastPlayed: "2023-03-08",
      category: "ps5_native_game",
      genre: "Survival/Craft",
      franchise: "Subnautica",
      isApp: false,
      trophy: {
        progress: 64,
        earned: { platinum: 0, gold: 3, silver: 8, bronze: 27 },
        total: 38,
        hasPlatinum: false,
        lastEarnedAt: "2023-03-08",
      },
    },
    {
      titleId: "DEMO-31",
      name: "The Last of Us™ Part II",
      platform: "PS4",
      hours: 38.49,
      playCount: 35,
      firstPlayed: "2020-06-18",
      lastPlayed: "2022-08-16",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2022-08-16",
      },
    },
    {
      titleId: "DEMO-32",
      name: "Overwatch®",
      platform: "PS4",
      hours: 38.36,
      playCount: 18,
      firstPlayed: "2022-12-11",
      lastPlayed: "2023-02-27",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 66,
        earned: { platinum: 0, gold: 3, silver: 9, bronze: 28 },
        total: 40,
        hasPlatinum: false,
        lastEarnedAt: "2023-02-27",
      },
    },
    {
      titleId: "DEMO-33",
      name: "EA SPORTS™ UFC® 4",
      platform: "PS4",
      hours: 36.31,
      playCount: 46,
      firstPlayed: "2020-08-13",
      lastPlayed: "2021-04-18",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 67,
        earned: { platinum: 0, gold: 3, silver: 9, bronze: 28 },
        total: 40,
        hasPlatinum: false,
        lastEarnedAt: "2021-04-18",
      },
    },
    {
      titleId: "DEMO-34",
      name: "The Alters",
      platform: "PS5",
      hours: 35.48,
      playCount: 30,
      firstPlayed: "2025-06-14",
      lastPlayed: "2025-08-24",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 68,
        earned: { platinum: 0, gold: 3, silver: 9, bronze: 29 },
        total: 41,
        hasPlatinum: false,
        lastEarnedAt: "2025-08-24",
      },
    },
    {
      titleId: "DEMO-35",
      name: "NBA 2K20",
      platform: "PS4",
      hours: 31.75,
      playCount: 37,
      firstPlayed: "2020-05-13",
      lastPlayed: "2020-06-11",
      category: "ps4_game",
      genre: "Sports",
      franchise: "NBA 2K",
      isApp: false,
      trophy: {
        progress: 69,
        earned: { platinum: 0, gold: 3, silver: 9, bronze: 29 },
        total: 41,
        hasPlatinum: false,
        lastEarnedAt: "2020-06-11",
      },
    },
    {
      titleId: "DEMO-36",
      name: "STAR WARS Jedi: Fallen Order™",
      platform: "PS5",
      hours: 25.16,
      playCount: 16,
      firstPlayed: "2026-02-08",
      lastPlayed: "2026-02-23",
      category: "ps5_native_game",
      genre: "Action-Adventure",
      franchise: "Star Wars",
      isApp: false,
      trophy: {
        progress: 100,
        earned: { platinum: 1, gold: 5, silver: 13, bronze: 42 },
        total: 61,
        hasPlatinum: true,
        lastEarnedAt: "2026-02-23",
      },
    },
    {
      titleId: "DEMO-37",
      name: "Crysis® Remastered",
      platform: "PS4",
      hours: 20.92,
      playCount: 14,
      firstPlayed: "2024-10-09",
      lastPlayed: "2024-10-26",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 30,
        earned: { platinum: 0, gold: 2, silver: 4, bronze: 13 },
        total: 19,
        hasPlatinum: false,
        lastEarnedAt: "2024-10-26",
      },
    },
    {
      titleId: "DEMO-38",
      name: "The Forest",
      platform: "PS4",
      hours: 18.56,
      playCount: 12,
      firstPlayed: "2020-09-06",
      lastPlayed: "2023-07-09",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 31,
        earned: { platinum: 0, gold: 2, silver: 4, bronze: 13 },
        total: 19,
        hasPlatinum: false,
        lastEarnedAt: "2023-07-09",
      },
    },
    {
      titleId: "DEMO-39",
      name: "Destiny 2",
      platform: "PS4",
      hours: 14.15,
      playCount: 10,
      firstPlayed: "2018-09-03",
      lastPlayed: "2020-08-02",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 32,
        earned: { platinum: 0, gold: 2, silver: 4, bronze: 13 },
        total: 19,
        hasPlatinum: false,
        lastEarnedAt: "2020-08-02",
      },
    },
    {
      titleId: "DEMO-40",
      name: "Warhammer 40,000: Space Marine 2",
      platform: "PS5",
      hours: 13.76,
      playCount: 11,
      firstPlayed: "2024-09-24",
      lastPlayed: "2024-11-15",
      category: "ps5_native_game",
      genre: "Shooter",
      franchise: "Warhammer 40K",
      isApp: false,
      trophy: {
        progress: 54,
        earned: { platinum: 0, gold: 3, silver: 7, bronze: 23 },
        total: 33,
        hasPlatinum: false,
        lastEarnedAt: "2024-11-15",
      },
    },
    {
      titleId: "DEMO-41",
      name: "METAL GEAR SOLID V: THE PHANTOM PAIN",
      platform: "PS4",
      hours: 13.14,
      playCount: 13,
      firstPlayed: "2025-02-26",
      lastPlayed: "2025-03-27",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 55,
        earned: { platinum: 0, gold: 3, silver: 7, bronze: 23 },
        total: 33,
        hasPlatinum: false,
        lastEarnedAt: "2025-03-27",
      },
    },
    {
      titleId: "DEMO-42",
      name: "Call of Duty®: WWII",
      platform: "PS4",
      hours: 12.75,
      playCount: 17,
      firstPlayed: "2017-08-25",
      lastPlayed: "2017-09-04",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 14,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 6 },
        total: 9,
        hasPlatinum: false,
        lastEarnedAt: "2017-09-04",
      },
    },
    {
      titleId: "DEMO-43",
      name: "Crysis 2 Remastered",
      platform: "PS4",
      hours: 11.63,
      playCount: 18,
      firstPlayed: "2024-10-26",
      lastPlayed: "2026-04-09",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 15,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 6 },
        total: 9,
        hasPlatinum: false,
        lastEarnedAt: "2026-04-09",
      },
    },
    {
      titleId: "DEMO-44",
      name: "HELLDIVERS™ 2",
      platform: "PS5",
      hours: 11.42,
      playCount: 7,
      firstPlayed: "2024-02-13",
      lastPlayed: "2024-02-29",
      category: "ps5_native_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 16,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 7 },
        total: 10,
        hasPlatinum: false,
        lastEarnedAt: "2024-02-29",
      },
    },
    {
      titleId: "DEMO-45",
      name: "VALORANT",
      platform: "PS5",
      hours: 9.8,
      playCount: 8,
      firstPlayed: "2024-06-23",
      lastPlayed: "2024-09-05",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 17,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 7 },
        total: 10,
        hasPlatinum: false,
        lastEarnedAt: "2024-09-05",
      },
    },
    {
      titleId: "DEMO-46",
      name: "Deus Ex: Mankind Divided™",
      platform: "PS4",
      hours: 9.68,
      playCount: 29,
      firstPlayed: "2023-07-11",
      lastPlayed: "2024-09-10",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 18,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 8 },
        total: 11,
        hasPlatinum: false,
        lastEarnedAt: "2024-09-10",
      },
    },
    {
      titleId: "DEMO-47",
      name: "Grand Theft Auto V (PlayStation®5)",
      platform: "PS5",
      hours: 9.56,
      playCount: 10,
      firstPlayed: "2022-05-28",
      lastPlayed: "2025-05-17",
      category: "ps5_native_game",
      genre: "Open World",
      franchise: "Grand Theft Auto",
      isApp: false,
      trophy: {
        progress: 19,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 8 },
        total: 11,
        hasPlatinum: false,
        lastEarnedAt: "2025-05-17",
      },
    },
    {
      titleId: "DEMO-48",
      name: "Battlefield™ 6",
      platform: "PS5",
      hours: 9.14,
      playCount: 6,
      firstPlayed: "2025-10-31",
      lastPlayed: "2025-11-09",
      category: "ps5_native_game",
      genre: "Shooter",
      franchise: "Battlefield",
      isApp: false,
      trophy: {
        progress: 20,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 8 },
        total: 12,
        hasPlatinum: false,
        lastEarnedAt: "2025-11-09",
      },
    },
    {
      titleId: "DEMO-49",
      name: "Prime Video",
      platform: "PS5",
      hours: 8.91,
      playCount: 12,
      firstPlayed: "2022-12-05",
      lastPlayed: "2023-07-10",
      category: "ps5_native_media_app",
      genre: "Other",
      isApp: false,
    },
    {
      titleId: "DEMO-50",
      name: "Rocket League®",
      platform: "PS4",
      hours: 8.15,
      playCount: 7,
      firstPlayed: "2021-07-16",
      lastPlayed: "2021-07-27",
      category: "unknown",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 43,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 18 },
        total: 26,
        hasPlatinum: false,
        lastEarnedAt: "2021-07-27",
      },
    },
    {
      titleId: "DEMO-51",
      name: "Overwatch®",
      platform: "PS5",
      hours: 7.25,
      playCount: 15,
      firstPlayed: "2022-10-05",
      lastPlayed: "2022-11-28",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 44,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 18 },
        total: 26,
        hasPlatinum: false,
        lastEarnedAt: "2022-11-28",
      },
    },
    {
      titleId: "DEMO-52",
      name: "Marvel's Avengers",
      platform: "PS4",
      hours: 6.86,
      playCount: 8,
      firstPlayed: "2020-08-17",
      lastPlayed: "2020-08-22",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 45,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 19 },
        total: 27,
        hasPlatinum: false,
        lastEarnedAt: "2020-08-22",
      },
    },
    {
      titleId: "DEMO-53",
      name: "Tom Clancy's Rainbow Six Siege",
      platform: "PS4",
      hours: 6.12,
      playCount: 18,
      firstPlayed: "2017-08-25",
      lastPlayed: "2020-06-13",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Tom Clancy",
      isApp: false,
      trophy: {
        progress: 46,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 19 },
        total: 27,
        hasPlatinum: false,
        lastEarnedAt: "2020-06-13",
      },
    },
    {
      titleId: "DEMO-54",
      name: "BioShock: The Collection",
      platform: "PS4",
      hours: 5.32,
      playCount: 7,
      firstPlayed: "2024-09-22",
      lastPlayed: "2024-10-08",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 47,
        earned: { platinum: 0, gold: 2, silver: 6, bronze: 20 },
        total: 28,
        hasPlatinum: false,
        lastEarnedAt: "2024-10-08",
      },
    },
    {
      titleId: "DEMO-55",
      name: "Dead by Daylight",
      platform: "PS4",
      hours: 4.97,
      playCount: 11,
      firstPlayed: "2018-08-08",
      lastPlayed: "2018-08-09",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 19,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 8 },
        total: 11,
        hasPlatinum: false,
        lastEarnedAt: "2018-08-09",
      },
    },
    {
      titleId: "DEMO-56",
      name: "Fall Guys: Ultimate Knockout",
      platform: "PS4",
      hours: 4.53,
      playCount: 6,
      firstPlayed: "2020-08-05",
      lastPlayed: "2020-08-10",
      category: "ps4_game",
      genre: "Indie/Casual",
      franchise: "Fall Guys",
      isApp: false,
      trophy: {
        progress: 20,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 8 },
        total: 12,
        hasPlatinum: false,
        lastEarnedAt: "2020-08-10",
      },
    },
    {
      titleId: "DEMO-57",
      name: "Apex Legends™",
      platform: "PS4",
      hours: 4.32,
      playCount: 3,
      firstPlayed: "2019-02-07",
      lastPlayed: "2019-02-09",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-58",
      name: "Destiny 2",
      platform: "PS5",
      hours: 4.3,
      playCount: 3,
      firstPlayed: "2023-10-20",
      lastPlayed: "2023-10-30",
      category: "ps5_native_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 22,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 9 },
        total: 13,
        hasPlatinum: false,
        lastEarnedAt: "2023-10-30",
      },
    },
    {
      titleId: "DEMO-59",
      name: "It Takes Two  PS4™ & PS5™",
      platform: "PS5",
      hours: 4.29,
      playCount: 3,
      firstPlayed: "2021-04-01",
      lastPlayed: "2021-04-03",
      category: "unknown",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 23,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2021-04-03",
      },
    },
    {
      titleId: "DEMO-60",
      name: "Rogue Company",
      platform: "PS4",
      hours: 3.84,
      playCount: 5,
      firstPlayed: "2020-10-31",
      lastPlayed: "2020-12-01",
      category: "unknown",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-61",
      name: "Battlefield™ V",
      platform: "PS4",
      hours: 3.54,
      playCount: 2,
      firstPlayed: "2021-05-14",
      lastPlayed: "2021-05-14",
      category: "unknown",
      genre: "Shooter",
      franchise: "Battlefield",
      isApp: false,
      trophy: {
        progress: 17,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 7 },
        total: 10,
        hasPlatinum: false,
        lastEarnedAt: "2021-05-14",
      },
    },
    {
      titleId: "DEMO-62",
      name: "NBA 2K20",
      platform: "PS4",
      hours: 3.08,
      playCount: 5,
      firstPlayed: "2019-08-21",
      lastPlayed: "2019-08-31",
      category: "ps4_game",
      genre: "Sports",
      franchise: "NBA 2K",
      isApp: false,
      trophy: {
        progress: 18,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 8 },
        total: 11,
        hasPlatinum: false,
        lastEarnedAt: "2019-08-31",
      },
    },
    {
      titleId: "DEMO-63",
      name: "The Witcher 3: Wild Hunt",
      platform: "PS5",
      hours: 3.07,
      playCount: 2,
      firstPlayed: "2024-12-25",
      lastPlayed: "2024-12-26",
      category: "ps5_native_game",
      genre: "RPG",
      franchise: "The Witcher",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-64",
      name: "Splitgate",
      platform: "PS4",
      hours: 2.94,
      playCount: 3,
      firstPlayed: "2022-09-14",
      lastPlayed: "2022-10-17",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 20,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 8 },
        total: 12,
        hasPlatinum: false,
        lastEarnedAt: "2022-10-17",
      },
    },
    {
      titleId: "DEMO-65",
      name: "Gears of War: Reloaded",
      platform: "PS5",
      hours: 2.91,
      playCount: 2,
      firstPlayed: "2025-08-26",
      lastPlayed: "2025-08-28",
      category: "ps5_native_game",
      genre: "Shooter",
      franchise: "Gears of War",
      isApp: false,
      trophy: {
        progress: 21,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 9 },
        total: 13,
        hasPlatinum: false,
        lastEarnedAt: "2025-08-28",
      },
    },
    {
      titleId: "DEMO-66",
      name: "Call of Duty®",
      platform: "PS5",
      hours: 2.78,
      playCount: 3,
      firstPlayed: "2022-09-18",
      lastPlayed: "2022-09-25",
      category: "ps5_native_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-67",
      name: "The Sims™ 4",
      platform: "PS4",
      hours: 2.78,
      playCount: 5,
      firstPlayed: "2020-09-20",
      lastPlayed: "2021-06-24",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 23,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2021-06-24",
      },
    },
    {
      titleId: "DEMO-68",
      name: "STAR WARS™ Battlefront™ II",
      platform: "PS4",
      hours: 2.47,
      playCount: 2,
      firstPlayed: "2020-06-15",
      lastPlayed: "2020-06-17",
      category: "ps4_game",
      genre: "Action-Adventure",
      franchise: "Star Wars",
      isApp: false,
      trophy: {
        progress: 24,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2020-06-17",
      },
    },
    {
      titleId: "DEMO-69",
      name: "FIFA 18",
      platform: "PS4",
      hours: 2.42,
      playCount: 5,
      firstPlayed: "2017-09-15",
      lastPlayed: "2017-09-30",
      category: "ps4_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-70",
      name: "NBA 2K19: The Prelude",
      platform: "PS4",
      hours: 2.38,
      playCount: 1,
      firstPlayed: "2018-08-31",
      lastPlayed: "2018-08-31",
      category: "not_found",
      genre: "Sports",
      franchise: "NBA 2K",
      isApp: false,
      trophy: {
        progress: 18,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 8 },
        total: 11,
        hasPlatinum: false,
        lastEarnedAt: "2018-08-31",
      },
    },
    {
      titleId: "DEMO-71",
      name: "Need for Speed™ Heat",
      platform: "PS4",
      hours: 2.14,
      playCount: 3,
      firstPlayed: "2020-10-07",
      lastPlayed: "2020-10-08",
      category: "ps4_game",
      genre: "Racing",
      franchise: "Need for Speed",
      isApp: false,
      trophy: {
        progress: 19,
        earned: { platinum: 0, gold: 1, silver: 2, bronze: 8 },
        total: 11,
        hasPlatinum: false,
        lastEarnedAt: "2020-10-08",
      },
    },
    {
      titleId: "DEMO-72",
      name: "THE FINALS",
      platform: "PS5",
      hours: 1.94,
      playCount: 3,
      firstPlayed: "2023-10-30",
      lastPlayed: "2023-11-05",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-73",
      name: "Sid Meier's Civilization VI",
      platform: "PS4",
      hours: 1.68,
      playCount: 4,
      firstPlayed: "2022-12-09",
      lastPlayed: "2024-10-04",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 21,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 9 },
        total: 13,
        hasPlatinum: false,
        lastEarnedAt: "2024-10-04",
      },
    },
    {
      titleId: "DEMO-74",
      name: "It Takes Two  PS4™ & PS5™",
      platform: "PS5",
      hours: 1.65,
      playCount: 1,
      firstPlayed: "2025-06-04",
      lastPlayed: "2025-06-04",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 22,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 9 },
        total: 13,
        hasPlatinum: false,
        lastEarnedAt: "2025-06-04",
      },
    },
    {
      titleId: "DEMO-75",
      name: "Brawlhalla",
      platform: "PS4",
      hours: 1.57,
      playCount: 2,
      firstPlayed: "2019-01-09",
      lastPlayed: "2019-01-09",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-76",
      name: "Call of Duty®: Modern Warfare®",
      platform: "PS4",
      hours: 1.51,
      playCount: 2,
      firstPlayed: "2019-08-23",
      lastPlayed: "2019-08-24",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 24,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2019-08-24",
      },
    },
    {
      titleId: "DEMO-77",
      name: "Call of Duty®: Modern Warfare®",
      platform: "PS4",
      hours: 1.31,
      playCount: 3,
      firstPlayed: "2019-09-20",
      lastPlayed: "2019-09-21",
      category: "ps4_game",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 25,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 11 },
        total: 15,
        hasPlatinum: false,
        lastEarnedAt: "2019-09-21",
      },
    },
    {
      titleId: "DEMO-78",
      name: "Control",
      platform: "PS4",
      hours: 1.15,
      playCount: 2,
      firstPlayed: "2021-08-11",
      lastPlayed: "2021-08-14",
      category: "unknown",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-79",
      name: "Marathon Server Slam",
      platform: "PS5",
      hours: 1,
      playCount: 2,
      firstPlayed: "2026-02-28",
      lastPlayed: "2026-03-01",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 27,
        earned: { platinum: 0, gold: 1, silver: 4, bronze: 11 },
        total: 16,
        hasPlatinum: false,
        lastEarnedAt: "2026-03-01",
      },
    },
    {
      titleId: "DEMO-80",
      name: "Call of Duty®: Vanguard",
      platform: "PS4",
      hours: 0.95,
      playCount: 1,
      firstPlayed: "2021-08-28",
      lastPlayed: "2021-08-28",
      category: "unknown",
      genre: "Shooter",
      franchise: "Call of Duty",
      isApp: false,
      trophy: {
        progress: 20,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 8 },
        total: 12,
        hasPlatinum: false,
        lastEarnedAt: "2021-08-28",
      },
    },
    {
      titleId: "DEMO-81",
      name: "Anthem™",
      platform: "PS4",
      hours: 0.9,
      playCount: 1,
      firstPlayed: "2019-02-03",
      lastPlayed: "2019-02-03",
      category: "ps4_game",
      genre: "Shooter",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-82",
      name: "Need for Speed™ Unbound",
      platform: "PS5",
      hours: 0.73,
      playCount: 4,
      firstPlayed: "2026-02-26",
      lastPlayed: "2026-04-04",
      category: "ps5_native_game",
      genre: "Racing",
      franchise: "Need for Speed",
      isApp: false,
      trophy: {
        progress: 22,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 9 },
        total: 13,
        hasPlatinum: false,
        lastEarnedAt: "2026-04-04",
      },
    },
    {
      titleId: "DEMO-83",
      name: "PRO EVOLUTION SOCCER 2018",
      platform: "PS4",
      hours: 0.71,
      playCount: 2,
      firstPlayed: "2017-09-02",
      lastPlayed: "2017-09-05",
      category: "not_found",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 23,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2017-09-05",
      },
    },
    {
      titleId: "DEMO-84",
      name: "Horizon Zero Dawn™",
      platform: "PS4",
      hours: 0.65,
      playCount: 1,
      firstPlayed: "2021-04-21",
      lastPlayed: "2021-04-21",
      category: "unknown",
      genre: "Open World",
      franchise: "Horizon",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-85",
      name: "FIFA 20",
      platform: "PS4",
      hours: 0.65,
      playCount: 2,
      firstPlayed: "2019-09-10",
      lastPlayed: "2019-09-25",
      category: "ps4_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 25,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 11 },
        total: 15,
        hasPlatinum: false,
        lastEarnedAt: "2019-09-25",
      },
    },
    {
      titleId: "DEMO-86",
      name: "UNO®",
      platform: "PS5",
      hours: 0.6,
      playCount: 4,
      firstPlayed: "2026-04-04",
      lastPlayed: "2026-05-08",
      category: "ps5_native_game",
      genre: "Indie/Casual",
      isApp: false,
      trophy: {
        progress: 26,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 11 },
        total: 15,
        hasPlatinum: false,
        lastEarnedAt: "2026-05-08",
      },
    },
    {
      titleId: "DEMO-87",
      name: "Chained Up Together",
      platform: "PS4",
      hours: 0.54,
      playCount: 2,
      firstPlayed: "2026-02-25",
      lastPlayed: "2026-02-25",
      category: "ps4_game",
      genre: "Indie/Casual",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-88",
      name: "Until Dawn™",
      platform: "PS4",
      hours: 0.22,
      playCount: 1,
      firstPlayed: "2017-07-21",
      lastPlayed: "2017-07-21",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 28,
        earned: { platinum: 0, gold: 1, silver: 4, bronze: 12 },
        total: 17,
        hasPlatinum: false,
        lastEarnedAt: "2017-07-21",
      },
    },
    {
      titleId: "DEMO-89",
      name: "EA Play Hub",
      platform: "PS4",
      hours: 0.18,
      playCount: 4,
      firstPlayed: "2019-09-20",
      lastPlayed: "2020-10-07",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
    },
    {
      titleId: "DEMO-90",
      name: "Subnautica",
      platform: "PS5",
      hours: 0.17,
      playCount: 0,
      firstPlayed: "2022-05-22",
      lastPlayed: "2022-05-22",
      category: "ps5_native_game",
      genre: "Survival/Craft",
      franchise: "Subnautica",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-91",
      name: "Frozen Free Fall: Snowball Fight",
      platform: "PS4",
      hours: 0.16,
      playCount: 1,
      firstPlayed: "2017-08-31",
      lastPlayed: "2017-08-31",
      category: "ps4_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 23,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2017-08-31",
      },
    },
    {
      titleId: "DEMO-92",
      name: "UFL",
      platform: "PS5",
      hours: 0.15,
      playCount: 1,
      firstPlayed: "2024-06-07",
      lastPlayed: "2024-06-07",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 24,
        earned: { platinum: 0, gold: 1, silver: 3, bronze: 10 },
        total: 14,
        hasPlatinum: false,
        lastEarnedAt: "2024-06-07",
      },
    },
    {
      titleId: "DEMO-93",
      name: "Need for Speed™ Payback",
      platform: "PS4",
      hours: 0.15,
      playCount: 2,
      firstPlayed: "2020-10-07",
      lastPlayed: "2020-10-07",
      category: "ps4_game",
      genre: "Racing",
      franchise: "Need for Speed",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-94",
      name: "Share Factory Studio",
      platform: "PS5",
      hours: 0.06,
      playCount: 2,
      firstPlayed: "2025-03-08",
      lastPlayed: "2025-03-08",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
    },
    {
      titleId: "DEMO-95",
      name: "PAYDAY 3",
      platform: "PS5",
      hours: 0.06,
      playCount: 2,
      firstPlayed: "2025-02-26",
      lastPlayed: "2025-02-28",
      category: "ps5_native_game",
      genre: "Other",
      isApp: false,
      trophy: {
        progress: 27,
        earned: { platinum: 0, gold: 1, silver: 4, bronze: 11 },
        total: 16,
        hasPlatinum: false,
        lastEarnedAt: "2025-02-28",
      },
    },
    {
      titleId: "DEMO-96",
      name: "Gears of War: Reloaded",
      platform: "PS5",
      hours: 0,
      playCount: 1,
      firstPlayed: "2025-08-27",
      lastPlayed: "2025-08-27",
      category: "ps5_native_game",
      genre: "Shooter",
      franchise: "Gears of War",
      isApp: false,
      trophy: {
        progress: 0,
        earned: { platinum: 0, gold: 0, silver: 0, bronze: 0 },
        total: 0,
        hasPlatinum: false,
      },
    },
    {
      titleId: "DEMO-97",
      name: "FIFA 22",
      platform: "PS5",
      hours: 0,
      playCount: 0,
      firstPlayed: "2022-05-21",
      lastPlayed: "2022-05-21",
      category: "ps5_native_game",
      genre: "Sports",
      franchise: "FIFA / EA FC",
      isApp: false,
      trophy: {
        progress: 29,
        earned: { platinum: 0, gold: 1, silver: 4, bronze: 12 },
        total: 17,
        hasPlatinum: false,
        lastEarnedAt: "2022-05-21",
      },
    },
  ],
  fetchedAt: "2026-06-27T00:00:00.000Z",
  meta: {
    totalGames: 98,
    totalHours: 7687.75,
    totalSessions: 5966,
    appsExcluded: [
      {
        name: "YouTube",
        hours: 2133.23,
      },
      {
        name: "Netflix",
        hours: 237.55,
      },
      {
        name: "BBC iPlayer",
        hours: 58.01,
      },
      {
        name: "NOW",
        hours: 35.89,
      },
      {
        name: "YouTube",
        hours: 29.44,
      },
      {
        name: "Apple TV",
        hours: 8.65,
      },
      {
        name: "Apple Music",
        hours: 4.4,
      },
      {
        name: "BBC iPlayer",
        hours: 4.34,
      },
      {
        name: "Spotify",
        hours: 3.42,
      },
      {
        name: "Netflix",
        hours: 3.01,
      },
      {
        name: "Channel 4",
        hours: 2.96,
      },
      {
        name: "Twitch",
        hours: 2.74,
      },
      {
        name: "Disney+",
        hours: 0.04,
      },
      {
        name: "Sky Go",
        hours: 0.01,
      },
    ],
    firstEverPlayed: "2017-06-26",
    span: {
      from: "2017-06-26",
      to: "2026-06-25",
    },
  },
  isDemo: true,
  trophiesUnavailable: false,
};
